sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 12345678
  alioss:
    endpoint: ${AliOSS.endpoint}
    access-key-id: ${AliOSS.accessKeyId}
    access-key-secret: ${AliOSS.accessKeySecret}
    bucket-name: ${AliOSS.bucketName}

